package com.zaptransfer.android.crypto

import com.goterl.lazysodium.LazySodiumJava
import com.goterl.lazysodium.SodiumJava
import com.google.gson.JsonArray
import com.google.gson.JsonObject
import com.google.gson.JsonParser
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Test
import java.security.MessageDigest

/**
 * Byte-exact test vector suite for [BeamCipher].
 *
 * Loads `crypto-v1.json` from `src/test/resources/` (a mirror of
 * `server/test-vectors/crypto-v1.json` generated by the Python reference)
 * and asserts that every derivation and AEAD output matches the canonical
 * bytes. If any assertion fails, Android has drifted from the spec and
 * cross-client transfers will break.
 *
 * Runs as a plain JVM unit test using lazysodium-java (no emulator required).
 * Uses Gson instead of org.json because the Android test stub returns default
 * values for every org.json call under `isReturnDefaultValues = true`.
 */
class BeamCipherTest {

    private val cipher = BeamCipher(LazySodiumJava(SodiumJava()))

    private fun loadVectors(): JsonObject {
        val stream = javaClass.classLoader!!.getResourceAsStream("crypto-v1.json")
            ?: error("crypto-v1.json not found on test classpath")
        val text = stream.bufferedReader().use { it.readText() }
        return JsonParser.parseString(text).asJsonObject
    }

    private fun hex(b: ByteArray): String {
        val sb = StringBuilder(b.size * 2)
        for (x in b) sb.append(String.format("%02x", x.toInt() and 0xff))
        return sb.toString()
    }

    private fun fromHex(s: String): ByteArray {
        require(s.length % 2 == 0)
        val out = ByteArray(s.length / 2)
        for (i in out.indices) {
            out[i] = ((Character.digit(s[i * 2], 16) shl 4) or
                Character.digit(s[i * 2 + 1], 16)).toByte()
        }
        return out
    }

    private fun sha256Hex(b: ByteArray): String =
        hex(MessageDigest.getInstance("SHA-256").digest(b))

    private fun JsonObject.s(key: String): String = get(key).asString
    private fun JsonObject.i(key: String): Int = get(key).asInt
    private fun JsonObject.o(key: String): JsonObject = getAsJsonObject(key)
    private fun JsonObject.a(key: String): JsonArray = getAsJsonArray(key)

    @Test
    fun vectorsMatch() {
        val v = loadVectors()

        // ---- version ----
        assertEquals("protocol version", 1, v.i("version"))
        assertEquals("BeamCipher.PROTOCOL_VERSION", 1, BeamCipher.PROTOCOL_VERSION)

        // ---- inputs ----
        val inputs = v.o("inputs")
        val staticSkA  = fromHex(inputs.s("staticSkA"))
        val staticPkA  = fromHex(inputs.s("staticPkA"))
        val staticSkB  = fromHex(inputs.s("staticSkB"))
        val staticPkB  = fromHex(inputs.s("staticPkB"))
        val ephSkA     = fromHex(inputs.s("ephSkA"))
        val ephPkA     = fromHex(inputs.s("ephPkA"))
        val ephSkB     = fromHex(inputs.s("ephSkB"))
        val ephPkB     = fromHex(inputs.s("ephPkB"))
        val salt       = fromHex(inputs.s("salt"))
        val transferId = fromHex(inputs.s("transferId"))

        assertArrayEquals("staticPkA derived", staticPkA, cipher.x25519PublicKey(staticSkA))
        assertArrayEquals("staticPkB derived", staticPkB, cipher.x25519PublicKey(staticSkB))
        assertArrayEquals("ephPkA derived",    ephPkA,    cipher.x25519PublicKey(ephSkA))
        assertArrayEquals("ephPkB derived",    ephPkB,    cipher.x25519PublicKey(ephSkB))

        // ---- Triple-DH ----
        val tdh = v.o("tripleDH")
        val initiator = cipher.computeTripleDHInitiator(staticSkA, ephSkA, staticPkB, ephPkB)
        assertEquals("tripleDH.dh1 initiator", tdh.s("dh1"), hex(initiator.dh1))
        assertEquals("tripleDH.dh2 initiator", tdh.s("dh2"), hex(initiator.dh2))
        assertEquals("tripleDH.dh3 initiator", tdh.s("dh3"), hex(initiator.dh3))
        assertEquals("tripleDH.ikm initiator", tdh.s("ikm"), hex(initiator.ikm))

        val responder = cipher.computeTripleDHResponder(staticSkB, ephSkB, staticPkA, ephPkA)
        assertEquals("tripleDH.dh1 responder", tdh.s("dh1"), hex(responder.dh1))
        assertEquals("tripleDH.dh2 responder", tdh.s("dh2"), hex(responder.dh2))
        assertEquals("tripleDH.dh3 responder", tdh.s("dh3"), hex(responder.dh3))
        assertEquals("tripleDH.ikm responder", tdh.s("ikm"), hex(responder.ikm))

        // ---- Transcript ----
        val transcript = cipher.computeTranscript(
            version = v.i("version"),
            staticPkA = staticPkA,
            staticPkB = staticPkB,
            ephPkA = ephPkA,
            ephPkB = ephPkB,
            transferId = transferId,
        )
        assertEquals("transcript", v.s("transcript"), hex(transcript))

        // ---- Keys ----
        val keys = v.o("keys")
        val sessionKey = cipher.deriveSessionKey(initiator.ikm, salt, transcript)
        assertEquals("sessionKey", keys.s("sessionKey"), hex(sessionKey))
        val chunkKey = cipher.deriveChunkKey(sessionKey)
        assertEquals("chunkKey", keys.s("chunkKey"), hex(chunkKey))
        val metaKey = cipher.deriveMetaKey(sessionKey)
        assertEquals("metaKey", keys.s("metaKey"), hex(metaKey))

        // ---- Clipboard ----
        run {
            val clip = v.o("clipboard")
            val plaintext = fromHex(clip.s("plaintext"))

            val nonce = cipher.deriveNonce(chunkKey, 0L)
            assertEquals("clipboard.nonce", clip.s("nonce"), hex(nonce))

            val aad = cipher.buildAAD(BeamCipher.KIND_CLIPBOARD, 0, 1, transcript)
            assertEquals("clipboard.aad", clip.s("aad"), hex(aad))

            val ct = cipher.encryptClipboard(plaintext, chunkKey, transcript)
            assertEquals("clipboard.ciphertext", clip.s("ciphertext"), hex(ct))

            val decoded = cipher.decryptClipboard(fromHex(clip.s("ciphertext")), chunkKey, transcript)
            assertArrayEquals("clipboard.roundtrip", plaintext, decoded)
        }

        // ---- File metadata ----
        run {
            val meta = v.o("fileMetadata")
            val plaintext = fromHex(meta.s("plaintext"))

            val nonce = cipher.deriveNonce(metaKey, 0L)
            assertEquals("fileMetadata.nonce", meta.s("nonce"), hex(nonce))

            val aad = cipher.buildAAD(BeamCipher.KIND_FILE_METADATA, 0, 0, transcript)
            assertEquals("fileMetadata.aad", meta.s("aad"), hex(aad))

            val ct = cipher.encryptFileMetadata(plaintext, metaKey, transcript)
            assertEquals("fileMetadata.ciphertext", meta.s("ciphertext"), hex(ct))

            val decoded = cipher.decryptFileMetadata(fromHex(meta.s("ciphertext")), metaKey, transcript)
            assertArrayEquals("fileMetadata.roundtrip", plaintext, decoded)
        }

        // ---- File chunks ----
        run {
            val fc = v.o("fileChunks")
            val totalChunks = fc.i("totalChunks")
            val arr = fc.a("chunks")

            data class Pattern(val a: Int, val b: Int, val len: Int)
            val patterns = listOf(
                Pattern(37, 13, 200 * 1024),
                Pattern(91,  7, 200 * 1024),
                Pattern(53, 29, 12345),
            )

            for (i in patterns.indices) {
                val p = patterns[i]
                val idx = i + 1
                val vc = arr[i].asJsonObject
                assertEquals("fileChunk[$idx].index", idx, vc.i("index"))

                val plaintext = ByteArray(p.len)
                for (k in 0 until p.len) {
                    plaintext[k] = ((k * p.a + p.b) and 0xff).toByte()
                }
                assertEquals(
                    "fileChunk[$idx].plaintextSha256",
                    vc.s("plaintextSha256"),
                    sha256Hex(plaintext),
                )

                val nonce = cipher.deriveNonce(chunkKey, idx.toLong())
                assertEquals("fileChunk[$idx].nonce", vc.s("nonce"), hex(nonce))

                val aad = cipher.buildAAD(BeamCipher.KIND_FILE_CHUNK, idx, totalChunks, transcript)
                assertEquals("fileChunk[$idx].aad", vc.s("aad"), hex(aad))

                val ct = cipher.encryptFileChunk(plaintext, chunkKey, idx, totalChunks, transcript)
                assertEquals("fileChunk[$idx].ciphertextLen", vc.i("ciphertextLen"), ct.size)
                assertEquals(
                    "fileChunk[$idx].ciphertextSha256",
                    vc.s("ciphertextSha256"),
                    sha256Hex(ct),
                )

                val decoded = cipher.decryptFileChunk(ct, chunkKey, idx, totalChunks, transcript)
                assertEquals(
                    "fileChunk[$idx].roundtripSha256",
                    vc.s("plaintextSha256"),
                    sha256Hex(decoded),
                )
            }
        }

        // ---- Padding sanity ----
        run {
            val p = cipher.padPlaintext(byteArrayOf(1, 2, 3))
            val u = cipher.unpadPlaintext(p)
            assertArrayEquals("padding roundtrip", byteArrayOf(1, 2, 3), u)
        }
    }
}
